#!/bin/bash

# Set our 
ALL=false
RECURSIVE=false
VERBOSE=false

# User this in combination with xargs for recursion?
#echo $*

# Alternatively, some horrible crap like this...
#directories=`ls -p | grep "/"`
#echo $directories

if [ "$1" = "--help" ]; then
    echo -e "Usage: chext [OPTION] FILENAME EXTENSION\n  or:  chext [OPTION] EXTENSION1 EXTENSION2"
    exit 0
fi

while getopts ":arv" opt; do
    case $opt in
        a)
            ALL=true
            ;;
        r)
            RECURSIVE=true
            ;;
        v)
            VERBOSE=true
            ;;
        \?)
            echo "chext: Invalid option: -$OPTARG" >&2
            ;;
        :)
            echo "chext: Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

# Shift command line parameters so we can access positional arguments.
shift $((OPTIND - 1))


if $ALL; then
    for file in *.$1
    do 
        new_file="${file%.$1}.$2"
        mv "$file" "$new_file"
        if $VERBOSE; then
            echo "chext: '$file' -> '$new_file'"
        fi
    done
else
    new_file="${1%.${1##*.}}.$2"
    mv "$1" "$new_file"
    if $VERBOSE; then
        echo "chext: '$1' -> '$new_file'"
    fi
fi

